/** Public site URL, used in metadata, canonical links, sitemap and JSON-LD. */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://robsonx4.github.io').replace(/\/$/, '');

/** Path prefix when served from a subdirectory (GitHub Pages project site). */
export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const absolute = (path: string) => `${SITE_URL}${BASE_PATH}${path}`;

/** Per-language Open Graph image, generated by scripts/generate-images.mjs. */
export const ogImage = (lang: 'pt' | 'en', alt: string) => ({
  url: absolute(`/og-${lang}.png`),
  width: 1200,
  height: 630,
  alt,
});
